apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy-deployment
  labels:
    app: autodeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy
  template:
    metadata:
      labels:
        app: autodeploy
    spec:
      containers:
      - name: AutoDeploy
        image: autodeployapp/autodeploy:1.0
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: autodeploy-service
spec:
  selector:
    app: AutoDeploy
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8080
  type: NodePort
